development:
  api_key: 
  secret_key: 
  canvas_page_name:
  callback_url:
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url: 
  set_asset_host_to_callback_url: true   
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0
